FROM node:lts-alpine

WORKDIR /app

# Accept API base URL as build arg and env
ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
ARG VITE_MAP_API_KEY
ENV VITE_MAP_API_KEY=${VITE_MAP_API_KEY}

COPY package.json tsconfig.json remix.config.ts ./

RUN npm install

COPY app ./app

EXPOSE 5174

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5174"]


