"""initial migration

Revision ID: adffce76c6b4
Revises: 
Create Date: 2025-05-05 17:18:34.268074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adffce76c6b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('log_metadata', sa.JSON(), nullable=True),
    sa.Column('api_version', sa.String(), nullable=True),
    sa.Column('endpoint_category', sa.String(), nullable=True),
    sa.Column('request_size_bytes', sa.Integer(), nullable=True),
    sa.Column('response_size_bytes', sa.Integer(), nullable=True),
    sa.Column('is_error', sa.Boolean(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('client_type', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('parent_request_id', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_api_version'), 'audit_logs', ['api_version'], unique=False)
    op.create_index(op.f('ix_audit_logs_client_type'), 'audit_logs', ['client_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_country'), 'audit_logs', ['country'], unique=False)
    op.create_index(op.f('ix_audit_logs_duration_ms'), 'audit_logs', ['duration_ms'], unique=False)
    op.create_index(op.f('ix_audit_logs_endpoint_category'), 'audit_logs', ['endpoint_category'], unique=False)
    op.create_index(op.f('ix_audit_logs_error_type'), 'audit_logs', ['error_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_audit_logs_is_error'), 'audit_logs', ['is_error'], unique=False)
    op.create_index(op.f('ix_audit_logs_method'), 'audit_logs', ['method'], unique=False)
    op.create_index(op.f('ix_audit_logs_parent_request_id'), 'audit_logs', ['parent_request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource'], unique=False)
    op.create_index(op.f('ix_audit_logs_status_code'), 'audit_logs', ['status_code'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status_code'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_parent_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_method'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_is_error'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_error_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_endpoint_category'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_duration_ms'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_country'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_client_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_api_version'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
