# Use the base image from NodeJS 18 on debian to install the NREL certs
FROM node:20-bullseye AS certificates

# Install NREL root certs.
RUN curl -fsSLk -o /usr/local/share/ca-certificates/nrel_root.crt https://raw.github.nrel.gov/TADA/nrel-certs/v20180329/certs/nrel_root.pem && \
    curl -fsSLk -o /usr/local/share/ca-certificates/nrel_xca1.crt https://raw.github.nrel.gov/TADA/nrel-certs/v20180329/certs/nrel_xca1.pem && \
    update-ca-certificates

FROM node:20-alpine

# Copy the installed SSL certs into this image
COPY --from=certificates /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=certificates /usr/share/ca-certificates /usr/share/ca-certificates
COPY --from=certificates /usr/local/share/ca-certificates /usr/local/share/ca-certificates

# Declare ARGs after ENV and before using them
ARG VITE_API_BASE_URL

# Set environment variables
ENV NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt \
  VITE_API_BASE_URL=${VITE_API_BASE_URL}

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

EXPOSE 5173

CMD [ "yarn", "dev", "--host" ]
